### ISSUE TITLE
npm install fail with flow server not starting

### ISSUE THREAD

**Issue by skybach** [blockstack/cli-blockstack#14]
[2019-01-26 22:09:38] argv=~/codes/cli-blockstack/node_modules/flow-bin/flow-linux64-v0.66.0/flow start --temp-dir /tmp/flow ~/codes/cli-blockstack
[2019-01-26 22:09:38] Watching paths: 
	~/codes/cli-blockstack
	~/codes/blockstack.js
[2019-01-26 22:09:38] Initializing Server (This might take some time)
[2019-01-26 22:09:38] executable=~/codes/cli-blockstack/node_modules/flow-bin/flow-linux64-v0.66.0/flow
[2019-01-26 22:09:38] version=0.66.0
[2019-01-26 22:09:38] Parsing
[2019-01-26 22:09:40] Building package heap
<<<<<<<<
~/codes/cli-blockstack/node_modules/module-deps/test/invalid_pkg/package.json: Expected an object literal:
Raised by primitive operation at file "set.ml", line 339, characters 38-41
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "src/common/profiling/profiling_js.ml", line 431, characters 12-16
Called from file "src/services/inference/types_js.ml", line 57, characters 12-55
>>>>>>>>
Unhandled exception: Failure("~/codes/cli-blockstack/node_modules/module-deps/test/invalid_pkg/package.json: Expected an object literal")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "set.ml", line 339, characters 38-41
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "src/common/profiling/profiling_js.ml", line 431, characters 12-16
Called from file "src/services/inference/types_js.ml", line 57, characters 12-55
Called from file "src/services/inference/types_js.ml", line 1121, characters 11-55
Called from file "src/server/server.ml", line 45, characters 6-47
Called from file "src/common/profiling/profiling_js.ml", line 417, characters 12-23
Called from file "src/server/server.ml", line 43, characters 12-1023
Called from file "src/server/server.ml", line 183, characters 25-49
Called from file "src/server/server.ml", line 198, characters 14-29
Called from file "src/server/server.ml", line 155, characters 24-35
Called from file "src/server/server.ml", line 196, characters 12-149
Called from file "src/server/server.ml", line 206, characters 6-54

**Comment by jcnelson** [comment]
This is an environment error, not a bug in `cli-blockstack`.  Please confirm that your `.flowconfig` is present and looks like this:

```
[ignore]
.*/node_modules/documentation/*
.*/node_modules/.staging/*
.*/blockstack.js/*

[include]
../blockstack.js

[libs]

[options]

[lints]
```

If problem persists, please consider installing a newer version of `flow` and/or opening an issue against https://github.com/facebook/flow.

**Comment by skybach** [comment]
.flowconfig is definitely there since I just git clone the project and did not any fiddling with it.
I don't see flow being referenced anywhere in the package.json.

I did try reinstalling the flow-bin devDependencies from 0.66.0 to 0.91.0
Nope that did not help.
And like many, I have no idea what flow is being used for. The site says typescript checker, but not sure why that is needed for a cli. I just need to build and start using it.

Either there was some stuffs not mentioned in the README file or the dependencies are breaking.

**Comment by JacobHearst** [comment]
I'm having this same issue, my .flowconfig is exactly as posted but it just keeps losing connection to the server

**Comment by jcnelson** [comment]
Hmm...can you try adding `.*/node_modules/*` under the `[ignore]` heading?

**Comment by colindean** [comment]
I'm hitting this, too. `.flowconfig` is as given above. When I add the thing that @jcnelson suggests, it appears that modules will fail to resolve:

```
Monitor logs will go to /private/tmp/flow/zSUserszScolinzSSourcezScode-testszSblockstackzScli-blockstack.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/argparse.js:3:21

Cannot resolve module ajv.

     1│ /* @flow */
     2│
     3│ const Ajv = require('ajv');
     4│ const process = require('process');
     5│ const c32check = require('c32check');
     6│


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/argparse.js:4:25

Cannot resolve module process.

     1│ /* @flow */
     2│
     3│ const Ajv = require('ajv');
     4│ const process = require('process');
     5│ const c32check = require('c32check');
     6│
     7│ import os from 'os';

```

That, but repeated for what appears to be every module the app needs to load.

**Comment by colindean** [comment]
Content of the logs, appears that maybe there's another path that needs to be ignored:

```
cat /private/tmp/flow/zSUserszScolinzSSourcezScode-testszSblockstackzScli-blockstack.log
[2019-01-31 19:30:03] argv=/Users/colin/Source/code-tests/blockstack/cli-blockstack/node_modules/flow-bin/flow-osx-v0.66.0/flow start --temp-dir /tmp/flow /Users/colin/Source/code-tests/blockstack/cli-blockstack
[2019-01-31 19:30:03] Watching paths:
	/Users/colin/Source/code-tests/blockstack/cli-blockstack
	/Users/colin/Source/code-tests/blockstack/blockstack.js
[2019-01-31 19:30:03] Initializing Server (This might take some time)
[2019-01-31 19:30:03] executable=/Users/colin/Source/code-tests/blockstack/cli-blockstack/node_modules/flow-bin/flow-osx-v0.66.0/flow
[2019-01-31 19:30:03] version=0.66.0
[2019-01-31 19:30:03] Parsing
[2019-01-31 19:30:07] Building package heap
<<<<<<<<
/Users/colin/Source/code-tests/blockstack/cli-blockstack/node_modules/module-deps/test/invalid_pkg/package.json: Expected an object literal:
Raised by primitive operation at file "set.ml", line 339, characters 38-41
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "src/common/profiling/profiling_js.ml", line 431, characters 12-16
Called from file "src/services/inference/types_js.ml", line 57, characters 12-55
Called from file "src/services/inference/types_js.ml", line 1121, characters 11-55
Called from file "src/server/server.ml", line 45, characters 6-47
>>>>>>>>
Unhandled exception: Failure("/Users/colin/Source/code-tests/blockstack/cli-blockstack/node_modules/module-deps/test/invalid_pkg/package.json: Expected an object literal")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "set.ml", line 339, characters 38-41
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "set.ml", line 339, characters 28-36
Called from file "src/common/profiling/profiling_js.ml", line 431, characters 12-16
Called from file "src/services/inference/types_js.ml", line 57, characters 12-55
Called from file "src/services/inference/types_js.ml", line 1121, characters 11-55
Called from file "src/server/server.ml", line 45, characters 6-47
Called from file "src/common/profiling/profiling_js.ml", line 417, characters 12-23
Called from file "src/server/server.ml", line 43, characters 12-1023
Called from file "src/server/server.ml", line 183, characters 25-49
Called from file "src/server/server.ml", line 198, characters 14-29
Called from file "src/server/server.ml", line 155, characters 24-35
Called from file "src/server/server.ml", line 196, characters 12-149
Called from file "src/server/server.ml", line 206, characters 6-54
```

**Comment by colindean** [comment]
Found it, see #15 for what fixed flow for me.

**Comment by jcnelson** [comment]
Thanks @colindean!

@skybach @Origin does it work now?

**Comment by JacobHearst** [comment]
Yup!

**Comment by skybach** [comment]
yes! excellent!
thanks for everyone's input!

**Comment by larrysalibra** [comment]
I had a similar problem - npm install failing because of flow. I removed npm run flow from the relevant npm script as a workaround.

**Comment by zone117x** [comment]
I think this repo is going to be ported to Typescript as well. We've ran into many problems with flow.
