### ISSUE TITLE
Feature request: specify fee rate

### ISSUE THREAD

**Issue by john-light** [blockstack/cli-blockstack#21]
Currently it does not look like the CLI provides a way to set the fee rate (satoshis/ vbyte) paid when making bitcoin transactions. It would be nice to be able to set the fee rate, in case the default is under- or over-paying by a significant amount. This also allows users to set their fees based on their urgency: some may be in a hurry and want fast confirmations and therefore pay more, others may be happy with their tx taking an hour or longer to be confirmed and will therefore pay less.

**Comment by jcnelson** [comment]
You can use the `-F` option to set the fee rate.  If not supplied, it just contacts a public fee provider for an estimate.

**Comment by john-light** [comment]
Thanks @jcnelson! I did not see this in the `help` file but I do see it in the `argparse` file now. So to be sure, would I add `-F FEE_RATE` to any of my commands, for example:

`blockstack-cli renew example.id OWNER_KEY PAYMENT_KEY -F 5`

to pay 5 sats/vbyte to renew the name `example.id`? 

And to double check this I could add `-e` and get an estimate of the total cost like so:

`blockstack-cli renew example.id OWNER_KEY PAYMENT_KEY -F 5 -e`

?

**Comment by jcnelson** [comment]
It's not in the `help` output, but in the normal usage output:

```
$ blockstack-cli | grep -- -F
    -F FEE_RATE         Use the given transaction fee rate instead of the one
```

The fee rate is in satoshis/byte (`F 5` == 5 sat/byte).

You're correct about `-e` -- it prevents the transaction from being generated, and instead prints out a fee estimate.
