### ISSUE TITLE
profile_store fails with a 400

### ISSUE THREAD

**Issue by polluterofminds** [blockstack/cli-blockstack#22]
The profile_store command does not work at all. Have tried many different combination of how the CLI might expect the arguments and they all fail with a 400. Here's the example I expect to work: 

blockstack-cli profile_store ${ID-Address} ${pathToSignedProfile} ${ownerKey} https://hub.blockstack.org

**Comment by jcnelson** [comment]
Confirmed on my end.  Just pushed a possible fix.  Please let me know if it works? :pray:

**Comment by polluterofminds** [comment]
Confirmed this fixes the issue! Thanks for the quick work.
