### ISSUE TITLE
Add function to create did-configuration

### ISSUE THREAD

**Issue by friedger** [blockstack/cli-blockstack#29]
The identity foundation has published a specification to link DNS domains with DIDs: https://identity.foundation/specs/did-configuration/

This requires to create a JWT for the DID of the blockstack name.

There should be a method that produce the JSON of an entry described in the spec

The command line arguments should be:
`blockstack-cli get_did_configuration BLOCKSTACK_ID DOMAIN OWNER_KEY`

**Comment by dantrevino** [comment]
An example of how to use it on your website/app:
https://identity.foundation/.well-known/resources/did-configuration/demo/build/index.html

**Comment by jcnelson** [comment]
I left comments on #30.  Thanks guys!
