### ISSUE TITLE
Update to Stacks 2.0 token transfer transactions

### ISSUE THREAD

**Issue by yknl** [blockstack/cli-blockstack#35]
The `send_tokens` command needs to be updated to support Stacks 2.0 token transfer operations. It should integrate the [stacks-transactions](https://github.com/blockstack/stacks-transactions-js) lib to achieve this. 

As BTC is no longer required to fuel Stacks transactions, the following commands should no longer have anything to do with BTC:
`balance, convert_address, get_account_history, get_account_at`

The `send_btc` command should be removed.

Current `send_tokens` command:
```
blockstack-cli send_tokens SP1P10PS2T517S4SQGZT5WNX8R00G1ECTRKYCPMHY STACKS 12345 "$PAYMENT" "$BTC_PAYMENT"
    a9d387a925fb0ba7a725fb1e11f2c3f1647473699dd5a147c312e6453d233456
```

Stacks 2.0 `send_tokens` command:
```
blockstack-cli send_tokens SP1P10PS2T517S4SQGZT5WNX8R00G1ECTRKYCPMHY STACKS
12345 a9d387a925fb0ba7a725fb1e11f2c3f1647473699dd5a147c312e6453d233456
```

**Comment by stackatron** [comment]
@yknl can you please add some details, test cases, or todos here please.
