### ISSUE TITLE
CLI Testing placeholder

### ISSUE THREAD

**Issue by timstackblock** [blockstack/cli-blockstack#42]
Spoke to Ken today we discussed there will be some testing needed for the CLI wallet, "sending transactions like in the stacks wallet" with more specific use cases to come. 

I have created this issue as a place holder to flush out details of the test @yknl currently testing is blocked and we are not able to test. @yknl Please let me know when this task is ready for QA, we can track the progress here.

**Comment by timstackblock** [comment]
Hey guys just following up, are there any updates on testable functionality that I can get started with this week?

**Comment by aulneau** [comment]
@timstackblock I will write up a document today outlining how to properly test the explorer :)
