### ISSUE TITLE
cli feedback command

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/cli-blockstack#55]
## Feature request

Add a means for developers to leave feedback directly from the command line. I just dreamed this feature up, but think it could yield some valuable feedback, with super low friction. It could output directly into a dedicated Slack channel.

```sh
blockstack-cli feedback "wtf the make_keychain command doesn't work with argument --skldjf"
```

**Comment by agraebe** [comment]
Because this is pretty far out and could be captured in the unified CLI concept we were thinking about, I'd suggest we capture the suggestions in there and close this issue.
