### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/cli-blockstack#66]
**Describe the bug**
Upon
> $ npm install --global "https://github.com/blockstack/cli-blockstack#feature/stacks-2.0-tx"

I get

```
ImportError: No module named parser
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/blockstack-cli/node_modules/tiny-secp256k1
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.5 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I think it is a code / gpy issue on my machine (OS X) but sharing here if there is a previous issue documented here that can help. Thanks!

**Comment by agraebe** [comment]
@yknl, could you take a look?

**Comment by wileyj** [comment]
You'll need to have the macos xcode build-tools installed, I'd check that. Offhand, i would guess a missing `gcc` or some headers might be missing.
From the output, there should be a logfile that would have logged the errors building `tiny-secp256k`

**Comment by yknl** [comment]
Might be a NPM and python version issue. Older versions of node-gyp bundled with NPM only supports python 2.7. Newer versions should support python 3. Updating NPM should address this issue. 

Check versions:
`python --version`
`npm -v`

Updating NPM if using nvm:
`nvm install-latest-npm` 

or `npm install npm`

**Comment by muneeb-ali** [comment]
I'm on Python 2.7.13 and npm 6.11.3

> npm install npm

Solved this. Thanks @yknl !
